In [1]:
import numpy as np

# **Practice** *Optional* 

This section is to display some of the functions you'll be using for the challenges. You can read the documentation for all functions [here](https://numpy.org/doc/stable/reference/arrays.html).

### *Lets begin with your basic array creation.*

In [2]:
first_arr = np.array([1,8,0,0,5,8,3])
first_arr

array([1, 8, 0, 0, 5, 8, 3])

*There are also some quick methods to create int populated arrays. Here are 2 of those*

In [3]:
#array creation
ones_arr = np.ones(shape=(50,), dtype=int)
ones_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [4]:
range_arr = np.arange(start=5,stop=15,step=.7, dtype=float)
range_arr

array([ 5. ,  5.7,  6.4,  7.1,  7.8,  8.5,  9.2,  9.9, 10.6, 11.3, 12. ,
       12.7, 13.4, 14.1, 14.8])

### *The shape of an array*

*The shape of an array is defined by its rows and coloumns. The 3 functions we will cover here include*

    1. Getting the shape of an array

    2. Changing the shape of an array

    3. A quick method to change an array to be 1 dimensional

In [5]:
orig_arr = np.arange(1,13,dtype=int) #A range of integers in an array

print("New Array: ")
print(orig_arr)

print("\nArray Shape: ")
orig_arr.shape

New Array: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array Shape: 


(12,)

In [6]:
reshape_arr = orig_arr.reshape((3,4))

print("New Array: ")
print(reshape_arr)

print("\nArray Shape: ")
reshape_arr.shape

New Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array Shape: 


(3, 4)

In [7]:
flat_arr = reshape_arr.flatten()

print('New Array : ')
print(flat_arr)

print("\nArray Shape: ")
flat_arr.shape

New Array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array Shape: 


(12,)

### *Sorting an array*

*Arrays can also be sorted a number of ways. Here are 3 of those methods including*

    1. Basic sort function
    2. Retrieving the indices that sort an array
    3. Applying the sorting indices to an array

In [8]:
unsorted_arr = np.array([[1,2,3],[3,2,1],[2,1,3]])

print("New Array: ")
print(unsorted_arr)

New Array: 
[[1 2 3]
 [3 2 1]
 [2 1 3]]


In [9]:
#You define the axis you'd like to sort on
standard_sort_arr = np.sort(unsorted_arr, axis = 0)

print("New Array: ")
standard_sort_arr

New Array: 


array([[1, 1, 1],
       [2, 2, 3],
       [3, 2, 3]])

In [10]:
#Here's the array sorted on the last axis
standard_sort_arr = np.sort(unsorted_arr, axis = 1)

print("New Array: ")
standard_sort_arr

New Array: 


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
ind = np.argsort(unsorted_arr, axis=1)

print("Sorted Index array: ")
ind

Sorted Index array: 


array([[0, 1, 2],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

In [12]:
sorted_arr = np.take_along_axis(arr=unsorted_arr, indices=ind, axis=1) #Apply the sort indices to an array

print("New Array: ")
sorted_arr

New Array: 


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### *Math functions using arrays*

*There are many math functions that can be performed on a numpy array. We will go over a few of those including*

    1. Adding 2 1 dimensional array
    2. Adding a 1 dimensional array and a 2 dimensional array
    3. Finding the mean in an array
    4. Rounding array like objects


In [13]:
arr1 = np.arange(0,10)
arr2 = np.arange(0,100,10)

print("First array: \n", arr1,'\n')
print("Second array: \n", arr2,'\n')

print("Sum of both arrays: \n",(arr1+arr2))

First array: 
 [0 1 2 3 4 5 6 7 8 9] 

Second array: 
 [ 0 10 20 30 40 50 60 70 80 90] 

Sum of both arrays: 
 [ 0 11 22 33 44 55 66 77 88 99]


In [14]:
single_dim = np.array([5,5,5,5])
two_dim = np.array([[1,1,1,1],[3,3,3,3]])

print('First array shape : ', single_dim.shape, '\n', single_dim, '\n')
print('Second array shape : ', two_dim.shape, '\n', two_dim, '\n')

print('Sum of both arrays: \n', (single_dim+two_dim))

First array shape :  (4,) 
 [5 5 5 5] 

Second array shape :  (2, 4) 
 [[1 1 1 1]
 [3 3 3 3]] 

Sum of both arrays: 
 [[6 6 6 6]
 [8 8 8 8]]


In [15]:
print("Array: \n", arr1,'\n')

arr_mean = arr1.mean()

print("The mean of the array is: ", arr_mean)

Array: 
 [0 1 2 3 4 5 6 7 8 9] 

The mean of the array is:  4.5


In [16]:
print("Array: \n", range_arr, '\n')

ceil_arr = np.ceil(range_arr)
print("Array rounded up: \n", ceil_arr, '\n')

floor_arr = np.floor(range_arr)
print("Array rounded down: \n", floor_arr)

Array: 
 [ 5.   5.7  6.4  7.1  7.8  8.5  9.2  9.9 10.6 11.3 12.  12.7 13.4 14.1
 14.8] 

Array rounded up: 
 [ 5.  6.  7.  8.  8.  9. 10. 10. 11. 12. 13. 13. 14. 15. 15.] 

Array rounded down: 
 [ 5.  5.  6.  7.  7.  8.  9.  9. 10. 11. 12. 12. 13. 14. 14.]


### *Array manipulation*

*The last thing we will observe is*

    1. Deleting elements in an array
    2. Combining arrays

In [17]:
arr  = np.array([23,24,25,26,27,28,29,30,35,236,17])
print("Array: \n", arr, '\n')

updated_arr = np.delete(arr, [3,4,5,6,7])

print("Array after deletion: \n", updated_arr)

Array: 
 [ 23  24  25  26  27  28  29  30  35 236  17] 

Array after deletion: 
 [ 23  24  25  35 236  17]


In [18]:
arr1 =  np.array([[23,34,54],[12,42,122]])
arr2 =  np.array([[1,2,3],[4,5,6]])

print("First array: \n", arr1, '\n')

print("Second array: \n", arr2, '\n')

axis0 = np.concatenate((arr1, arr2), axis=0)
axis1 = np.concatenate((arr1, arr2), axis=1)

print("Concatenate over first axis: \n", axis0, '\n')
print("Concatenate over last axis: \n", axis1, '\n')

First array: 
 [[ 23  34  54]
 [ 12  42 122]] 

Second array: 
 [[1 2 3]
 [4 5 6]] 

Concatenate over first axis: 
 [[ 23  34  54]
 [ 12  42 122]
 [  1   2   3]
 [  4   5   6]] 

Concatenate over last axis: 
 [[ 23  34  54   1   2   3]
 [ 12  42 122   4   5   6]] 



# **numpyEx Class** *Do not expand, or exercise becomes boring*

*Please run all cells*

### numpyEx class definition

In [19]:
class numpyEx() :
  def __init__(self) :
      self.question = np.array(['the', 'pineapple', 'in', 'under', 'who', 'a', 'sea', 'lives'])
      self.array_half = np.array([[53, 322], [680, 73]])
      self.encryption = np.array([568, 224, 206, 278, 388])
      self.status = False

  def check_encryption(self, ind) :
    correct = np.array([4, 7, 2, 5, 1, 3, 0, 6])
    if(np.array_equal(ind, correct)) : 
      self.status = True
      print('Correct, Please apply this to the question.')
    else :
      print('Incorrect key')

  def check_answer(self, answer) :
    if(self.status == False) : print("Must decrypt question first!")
    else:
      if(answer.lower()== 'spongebob' or answer.lower()== 'spongebob squarepants') : print("Correct!")
      else : print("Incorrect, please try again.")

# ***Welcome***, *Expand me for a proper introduction*

*This packet will be used to practice some basic NumPy functions using scenarios.*

**Welcome explorer!** Congrats, you've done it, you've reached the center of the ruins. But alas, the secrets you've been searching for are encrypted with a puzzle. You have sufficient data and instructions on how to decrypt the final puzzle question, including:

*puzzle.question => Encrypted question you must decrypt and answer*

*puzzle.array_half => part of the encryption key (instructions will come later pertaining to this)*

*puzzle.encryption => part of the encryption key (instructions will come later pertaining to this)*

*All located within the numpyEx class*



*We trust you will be successful in your mission, good luck!*

# **The Challenge**

First thing first, let's see what we are working with. I've created the puzzle for you already, explorer. Feel free to observe the question.

In [20]:
puzzle = numpyEx()
puzzle.question

array(['the', 'pineapple', 'in', 'under', 'who', 'a', 'sea', 'lives'],
      dtype='<U9')

As you've just confirmed, the puzzle is scrambled. Now we could brute force the solution, but that's not the explorer way. For the first step of the decryption process, please create an array of five 1s (ex: [1, 1, 1, 1, 1]).

In [27]:
one_arr = np.ones(5,int)
one_arr

array([1, 1, 1, 1, 1])

Great!. Now we are going to have to get an array containing the sum of our created array and the stored encryption within the puzzle.

In [30]:
summed_arr = puzzle.encryption + one_arr
summed_arr

array([569, 225, 207, 279, 389])

Strange. You're array is looking a little long... We almost forgot! Remove the smallest element in the array.

In [35]:
sorted_puzzle = np.sort(summed_arr,0)
print(sorted_puzzle)
updated_puzzle = np.delete(sorted_puzzle,[0])
print(updated_puzzle)

[207 225 279 389 569]
[225 279 389 569]


Now it looks fabulous! Let's get back on track with these steps. Next find the rounded (ceiling) mean of your array and save it.

In [37]:
ceil_mean_puzzle = np.ceil(np.mean(updated_puzzle))
ceil_mean_puzzle

366.0

For the next part, you will have to replace the second element in the array with the calculated mean (remember, it is an array of ints)

In [38]:
updated_puzzle[1] = int(ceil_mean_puzzle)
updated_puzzle

array([225, 366, 389, 569])

We're almost there explore, just keep holding out!

Someone else has already solved the second half of the puzzle, but if we observe the shape of the stored array, there's a problem. Our calculated array and the other half have mismatching shapes!

We need to adjust the shape of our array to match the array_half already stored within the puzzle

In [47]:
half_puzzle = puzzle.array_half.flatten()
half_puzzle

array([ 53, 322, 680,  73])

Now that two array shapes match, we can combine the two arrays.

Remember, our array is the first half of the puzzle and the stored array is the second half

In [49]:
full_puzzle = np.concatenate((updated_puzzle,half_puzzle),axis=0)
full_puzzle

array([225, 366, 389, 569,  53, 322, 680,  73])

To get our final decryption key, we must transform our array to be 1-Dimensional and get the sorted indices

Before you proceed to apply the encryption to the puzzle question, please check it with this function. *Puzzle will not be completed without correct decryption key*

It's go time! Decrypt the puzzle question by applying the calculated sort order to the question array.

This is the final step explorer, check your answer against this function. You'll see if it's correct.

# **Finishing remarks**

Thank you explorer! We found the secrets and live to tell the tale. Who knew the answer would be so deep and profound. Generations will tell your story. Be proud explorer, we couldn't have done it without you!

